config/routes.rb
Rails.application.routes.draw do
  get 'person_details/get_person'
  post 'person_details/show_person'
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name_validator.rb
class  NameValidator
  include ActiveModel::Model
  include ActiveModel::Serialization
  attr_accessor :name
  validates :name, presence: true
  validates_with SatanValidator

  def valid
    valid?
  end

  # needed for serialization
  def attributes
   {'name' => nil, 'valid' => nil}
  end
end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true
  # validate :should_not_be_satan

  validates_with SatanValidator


  private

  # def should_not_be_satan
  #   errors.add(:name, ' should not be satan') if name.match(/satan/)
  # end
end

app/models/satan_validator.rb
class SatanValidator < ActiveModel::Validator
  def validate(record)
    if record.name.match(/satan/)
      record.errors.add :name, "Need a name starting with X please!"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :age)
    end
end

app/controllers/person_details_controller.rb
class PersonDetailsController < ApplicationController
  def get_person
  end

  def show_person
    @nv = NameValidator.new
    @nv.name = params[:name]
    @is_it_valid = @nv.valid?

    respond_to do |format|
        format.html {}
        format.json { render json: @nv.serializable_hash }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_details_helper.rb
module PersonDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Something</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.age %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @person.age %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/person_details/get_person.html.erb
<%= form_tag(action: :show_person, format: :json) do %>
  <%= text_field_tag :name %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/person_details/show_person.html.erb
<h1>PersonDetails#show_person</h1>
<p>Find me in app/views/person_details/show_person.html.erb</p>

<p>
<%= @is_it_valid %>
</p>